# Generated by Django 3.1.4 on 2020-12-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscriptions',
            name='purchase_date',
            field=models.DateTimeField(verbose_name='default=datetime.datetime.now()'),
        ),
    ]
