# Generated by Django 3.1.3 on 2020-12-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horse', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.horse'),
        ),
    ]
