# Generated by Django 3.1.3 on 2020-12-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('core', '0003_auto_20201225_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientSubscriptions',
            new_name='ClientSubscription',
        ),
    ]
