# Generated by Django 3.1.4 on 2020-12-24 23:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.owner')),
            ],
            options={
                'db_table': 'horses',
            },
        ),
        migrations.CreateModel(
            name='Stable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'stables',
            },
        ),
        migrations.CreateModel(
            name='StableOccupancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(default=datetime.datetime(2020, 12, 25, 1, 5, 59, 643898))),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.horse')),
                ('stable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.stable')),
            ],
            options={
                'db_table': 'stables_occupancy',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse.horse')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
    ]
