# Generated by Django 3.1.4 on 2020-12-24 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('horse', '0002_auto_20201225_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horses', to='user.owner'),
        ),
    ]
